# Generated by Django 2.2.1 on 2019-05-12 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_carttable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carttable',
            options={'verbose_name_plural': 'carttable'},
        ),
    ]
